"""Seed countries table with ISO 3166-1 data."""
import asyncio
import sys
from sqlalchemy import text
from database import AsyncSessionLocal

COUNTRIES = [
    # Châu Á
    ("AF", "Afghanistan", "Afghanistan", "Nam Á", "Châu Á", "🇦🇫"),
    ("AM", "Armenia", "Armenia", "Tây Á", "Châu Á", "🇦🇲"),
    ("AZ", "Azerbaijan", "Azerbaijan", "Tây Á", "Châu Á", "🇦🇿"),
    ("BH", "Bahrain", "Bahrain", "Tây Á", "Châu Á", "🇧🇭"),
    ("BD", "Bangladesh", "Bangladesh", "Nam Á", "Châu Á", "🇧🇩"),
    ("BT", "Bhutan", "Bhutan", "Nam Á", "Châu Á", "🇧🇹"),
    ("BN", "Brunei", "Brunei", "Đông Nam Á", "Châu Á", "🇧🇳"),
    ("KH", "Campuchia", "Cambodia", "Đông Nam Á", "Châu Á", "🇰🇭"),
    ("CN", "Trung Quốc", "China", "Đông Á", "Châu Á", "🇨🇳"),
    ("CY", "Síp", "Cyprus", "Tây Á", "Châu Á", "🇨🇾"),
    ("GE", "Georgia", "Georgia", "Tây Á", "Châu Á", "🇬🇪"),
    ("IN", "Ấn Độ", "India", "Nam Á", "Châu Á", "🇮🇳"),
    ("ID", "Indonesia", "Indonesia", "Đông Nam Á", "Châu Á", "🇮🇩"),
    ("IR", "Iran", "Iran", "Tây Á", "Châu Á", "🇮🇷"),
    ("IQ", "Iraq", "Iraq", "Tây Á", "Châu Á", "🇮🇶"),
    ("IL", "Israel", "Israel", "Tây Á", "Châu Á", "🇮🇱"),
    ("JP", "Nhật Bản", "Japan", "Đông Á", "Châu Á", "🇯🇵"),
    ("JO", "Jordan", "Jordan", "Tây Á", "Châu Á", "🇯🇴"),
    ("KZ", "Kazakhstan", "Kazakhstan", "Trung Á", "Châu Á", "🇰🇿"),
    ("KW", "Kuwait", "Kuwait", "Tây Á", "Châu Á", "🇰🇼"),
    ("KG", "Kyrgyzstan", "Kyrgyzstan", "Trung Á", "Châu Á", "🇰🇬"),
    ("LA", "Lào", "Laos", "Đông Nam Á", "Châu Á", "🇱🇦"),
    ("LB", "Lebanon", "Lebanon", "Tây Á", "Châu Á", "🇱🇧"),
    ("MY", "Malaysia", "Malaysia", "Đông Nam Á", "Châu Á", "🇲🇾"),
    ("MV", "Maldives", "Maldives", "Nam Á", "Châu Á", "🇲🇻"),
    ("MN", "Mông Cổ", "Mongolia", "Đông Á", "Châu Á", "🇲🇳"),
    ("MM", "Myanmar", "Myanmar", "Đông Nam Á", "Châu Á", "🇲🇲"),
    ("NP", "Nepal", "Nepal", "Nam Á", "Châu Á", "🇳🇵"),
    ("KP", "Triều Tiên", "North Korea", "Đông Á", "Châu Á", "🇰🇵"),
    ("OM", "Oman", "Oman", "Tây Á", "Châu Á", "🇴🇲"),
    ("PK", "Pakistan", "Pakistan", "Nam Á", "Châu Á", "🇵🇰"),
    ("PS", "Palestine", "Palestine", "Tây Á", "Châu Á", "🇵🇸"),
    ("PH", "Philippines", "Philippines", "Đông Nam Á", "Châu Á", "🇵🇭"),
    ("QA", "Qatar", "Qatar", "Tây Á", "Châu Á", "🇶🇦"),
    ("SA", "Saudi Arabia", "Saudi Arabia", "Tây Á", "Châu Á", "🇸🇦"),
    ("SG", "Singapore", "Singapore", "Đông Nam Á", "Châu Á", "🇸🇬"),
    ("KR", "Hàn Quốc", "South Korea", "Đông Á", "Châu Á", "🇰🇷"),
    ("LK", "Sri Lanka", "Sri Lanka", "Nam Á", "Châu Á", "🇱🇰"),
    ("SY", "Syria", "Syria", "Tây Á", "Châu Á", "🇸🇾"),
    ("TW", "Đài Loan", "Taiwan", "Đông Á", "Châu Á", "🇹🇼"),
    ("TJ", "Tajikistan", "Tajikistan", "Trung Á", "Châu Á", "🇹🇯"),
    ("TH", "Thái Lan", "Thailand", "Đông Nam Á", "Châu Á", "🇹🇭"),
    ("TL", "Timor-Leste", "Timor-Leste", "Đông Nam Á", "Châu Á", "🇹🇱"),
    ("TR", "Thổ Nhĩ Kỳ", "Turkey", "Tây Á", "Châu Á", "🇹🇷"),
    ("TM", "Turkmenistan", "Turkmenistan", "Trung Á", "Châu Á", "🇹🇲"),
    ("AE", "UAE", "United Arab Emirates", "Tây Á", "Châu Á", "🇦🇪"),
    ("UZ", "Uzbekistan", "Uzbekistan", "Trung Á", "Châu Á", "🇺🇿"),
    ("VN", "Việt Nam", "Vietnam", "Đông Nam Á", "Châu Á", "🇻🇳"),
    ("YE", "Yemen", "Yemen", "Tây Á", "Châu Á", "🇾🇪"),
    # Châu Âu
    ("AL", "Albania", "Albania", "Đông Nam Âu", "Châu Âu", "🇦🇱"),
    ("AD", "Andorra", "Andorra", "Tây Âu", "Châu Âu", "🇦🇩"),
    ("AT", "Áo", "Austria", "Trung Âu", "Châu Âu", "🇦🇹"),
    ("BY", "Belarus", "Belarus", "Đông Âu", "Châu Âu", "🇧🇾"),
    ("BE", "Bỉ", "Belgium", "Tây Âu", "Châu Âu", "🇧🇪"),
    ("BA", "Bosnia và Herzegovina", "Bosnia and Herzegovina", "Đông Nam Âu", "Châu Âu", "🇧🇦"),
    ("BG", "Bulgaria", "Bulgaria", "Đông Nam Âu", "Châu Âu", "🇧🇬"),
    ("HR", "Croatia", "Croatia", "Đông Nam Âu", "Châu Âu", "🇭🇷"),
    ("CZ", "Cộng hòa Séc", "Czech Republic", "Trung Âu", "Châu Âu", "🇨🇿"),
    ("DK", "Đan Mạch", "Denmark", "Bắc Âu", "Châu Âu", "🇩🇰"),
    ("EE", "Estonia", "Estonia", "Bắc Âu", "Châu Âu", "🇪🇪"),
    ("FI", "Phần Lan", "Finland", "Bắc Âu", "Châu Âu", "🇫🇮"),
    ("FR", "Pháp", "France", "Tây Âu", "Châu Âu", "🇫🇷"),
    ("DE", "Đức", "Germany", "Trung Âu", "Châu Âu", "🇩🇪"),
    ("GR", "Hy Lạp", "Greece", "Đông Nam Âu", "Châu Âu", "🇬🇷"),
    ("HU", "Hungary", "Hungary", "Trung Âu", "Châu Âu", "🇭🇺"),
    ("IS", "Iceland", "Iceland", "Bắc Âu", "Châu Âu", "🇮🇸"),
    ("IE", "Ireland", "Ireland", "Tây Âu", "Châu Âu", "🇮🇪"),
    ("IT", "Ý", "Italy", "Nam Âu", "Châu Âu", "🇮🇹"),
    ("XK", "Kosovo", "Kosovo", "Đông Nam Âu", "Châu Âu", "🇽🇰"),
    ("LV", "Latvia", "Latvia", "Bắc Âu", "Châu Âu", "🇱🇻"),
    ("LI", "Liechtenstein", "Liechtenstein", "Trung Âu", "Châu Âu", "🇱🇮"),
    ("LT", "Lithuania", "Lithuania", "Bắc Âu", "Châu Âu", "🇱🇹"),
    ("LU", "Luxembourg", "Luxembourg", "Tây Âu", "Châu Âu", "🇱🇺"),
    ("MT", "Malta", "Malta", "Nam Âu", "Châu Âu", "🇲🇹"),
    ("MD", "Moldova", "Moldova", "Đông Âu", "Châu Âu", "🇲🇩"),
    ("MC", "Monaco", "Monaco", "Tây Âu", "Châu Âu", "🇲🇨"),
    ("ME", "Montenegro", "Montenegro", "Đông Nam Âu", "Châu Âu", "🇲🇪"),
    ("NL", "Hà Lan", "Netherlands", "Tây Âu", "Châu Âu", "🇳🇱"),
    ("MK", "Bắc Macedonia", "North Macedonia", "Đông Nam Âu", "Châu Âu", "🇲🇰"),
    ("NO", "Na Uy", "Norway", "Bắc Âu", "Châu Âu", "🇳🇴"),
    ("PL", "Ba Lan", "Poland", "Trung Âu", "Châu Âu", "🇵🇱"),
    ("PT", "Bồ Đào Nha", "Portugal", "Nam Âu", "Châu Âu", "🇵🇹"),
    ("RO", "Romania", "Romania", "Đông Âu", "Châu Âu", "🇷🇴"),
    ("RU", "Nga", "Russia", "Đông Âu", "Châu Âu", "🇷🇺"),
    ("SM", "San Marino", "San Marino", "Nam Âu", "Châu Âu", "🇸🇲"),
    ("RS", "Serbia", "Serbia", "Đông Nam Âu", "Châu Âu", "🇷🇸"),
    ("SK", "Slovakia", "Slovakia", "Trung Âu", "Châu Âu", "🇸🇰"),
    ("SI", "Slovenia", "Slovenia", "Trung Âu", "Châu Âu", "🇸🇮"),
    ("ES", "Tây Ban Nha", "Spain", "Nam Âu", "Châu Âu", "🇪🇸"),
    ("SE", "Thụy Điển", "Sweden", "Bắc Âu", "Châu Âu", "🇸🇪"),
    ("CH", "Thụy Sĩ", "Switzerland", "Trung Âu", "Châu Âu", "🇨🇭"),
    ("UA", "Ukraine", "Ukraine", "Đông Âu", "Châu Âu", "🇺🇦"),
    ("GB", "Anh", "United Kingdom", "Tây Âu", "Châu Âu", "🇬🇧"),
    ("VA", "Vatican", "Vatican City", "Nam Âu", "Châu Âu", "🇻🇦"),
    # Bắc Mỹ
    ("AG", "Antigua và Barbuda", "Antigua and Barbuda", "Caribbean", "Bắc Mỹ", "🇦🇬"),
    ("BS", "Bahamas", "Bahamas", "Caribbean", "Bắc Mỹ", "🇧🇸"),
    ("BB", "Barbados", "Barbados", "Caribbean", "Bắc Mỹ", "🇧🇧"),
    ("BZ", "Belize", "Belize", "Trung Mỹ", "Bắc Mỹ", "🇧🇿"),
    ("CA", "Canada", "Canada", "Bắc Mỹ", "Bắc Mỹ", "🇨🇦"),
    ("CR", "Costa Rica", "Costa Rica", "Trung Mỹ", "Bắc Mỹ", "🇨🇷"),
    ("CU", "Cuba", "Cuba", "Caribbean", "Bắc Mỹ", "🇨🇺"),
    ("DM", "Dominica", "Dominica", "Caribbean", "Bắc Mỹ", "🇩🇲"),
    ("DO", "Cộng hòa Dominican", "Dominican Republic", "Caribbean", "Bắc Mỹ", "🇩🇴"),
    ("SV", "El Salvador", "El Salvador", "Trung Mỹ", "Bắc Mỹ", "🇸🇻"),
    ("GD", "Grenada", "Grenada", "Caribbean", "Bắc Mỹ", "🇬🇩"),
    ("GT", "Guatemala", "Guatemala", "Trung Mỹ", "Bắc Mỹ", "🇬🇹"),
    ("HT", "Haiti", "Haiti", "Caribbean", "Bắc Mỹ", "🇭🇹"),
    ("HN", "Honduras", "Honduras", "Trung Mỹ", "Bắc Mỹ", "🇭🇳"),
    ("JM", "Jamaica", "Jamaica", "Caribbean", "Bắc Mỹ", "🇯🇲"),
    ("MX", "Mexico", "Mexico", "Bắc Mỹ", "Bắc Mỹ", "🇲🇽"),
    ("NI", "Nicaragua", "Nicaragua", "Trung Mỹ", "Bắc Mỹ", "🇳🇮"),
    ("PA", "Panama", "Panama", "Trung Mỹ", "Bắc Mỹ", "🇵🇦"),
    ("KN", "Saint Kitts và Nevis", "Saint Kitts and Nevis", "Caribbean", "Bắc Mỹ", "🇰🇳"),
    ("LC", "Saint Lucia", "Saint Lucia", "Caribbean", "Bắc Mỹ", "🇱🇨"),
    ("VC", "Saint Vincent và Grenadines", "Saint Vincent and the Grenadines", "Caribbean", "Bắc Mỹ", "🇻🇨"),
    ("TT", "Trinidad và Tobago", "Trinidad and Tobago", "Caribbean", "Bắc Mỹ", "🇹🇹"),
    ("US", "Hoa Kỳ", "United States", "Bắc Mỹ", "Bắc Mỹ", "🇺🇸"),
    # Nam Mỹ
    ("AR", "Argentina", "Argentina", "Nam Mỹ", "Nam Mỹ", "🇦🇷"),
    ("BO", "Bolivia", "Bolivia", "Nam Mỹ", "Nam Mỹ", "🇧🇴"),
    ("BR", "Brazil", "Brazil", "Nam Mỹ", "Nam Mỹ", "🇧🇷"),
    ("CL", "Chile", "Chile", "Nam Mỹ", "Nam Mỹ", "🇨🇱"),
    ("CO", "Colombia", "Colombia", "Nam Mỹ", "Nam Mỹ", "🇨🇴"),
    ("EC", "Ecuador", "Ecuador", "Nam Mỹ", "Nam Mỹ", "🇪🇨"),
    ("GY", "Guyana", "Guyana", "Nam Mỹ", "Nam Mỹ", "🇬🇾"),
    ("PY", "Paraguay", "Paraguay", "Nam Mỹ", "Nam Mỹ", "🇵🇾"),
    ("PE", "Peru", "Peru", "Nam Mỹ", "Nam Mỹ", "🇵🇪"),
    ("SR", "Suriname", "Suriname", "Nam Mỹ", "Nam Mỹ", "🇸🇷"),
    ("UY", "Uruguay", "Uruguay", "Nam Mỹ", "Nam Mỹ", "🇺🇾"),
    ("VE", "Venezuela", "Venezuela", "Nam Mỹ", "Nam Mỹ", "🇻🇪"),
    # Châu Phi
    ("DZ", "Algeria", "Algeria", "Bắc Phi", "Châu Phi", "🇩🇿"),
    ("AO", "Angola", "Angola", "Trung Phi", "Châu Phi", "🇦🇴"),
    ("BJ", "Benin", "Benin", "Tây Phi", "Châu Phi", "🇧🇯"),
    ("BW", "Botswana", "Botswana", "Nam Phi", "Châu Phi", "🇧🇼"),
    ("BF", "Burkina Faso", "Burkina Faso", "Tây Phi", "Châu Phi", "🇧🇫"),
    ("BI", "Burundi", "Burundi", "Đông Phi", "Châu Phi", "🇧🇮"),
    ("CV", "Cabo Verde", "Cabo Verde", "Tây Phi", "Châu Phi", "🇨🇻"),
    ("CM", "Cameroon", "Cameroon", "Trung Phi", "Châu Phi", "🇨🇲"),
    ("CF", "Cộng hòa Trung Phi", "Central African Republic", "Trung Phi", "Châu Phi", "🇨🇫"),
    ("TD", "Chad", "Chad", "Trung Phi", "Châu Phi", "🇹🇩"),
    ("KM", "Comoros", "Comoros", "Đông Phi", "Châu Phi", "🇰🇲"),
    ("CG", "Cộng hòa Congo", "Republic of the Congo", "Trung Phi", "Châu Phi", "🇨🇬"),
    ("CD", "Cộng hòa Dân chủ Congo", "DR Congo", "Trung Phi", "Châu Phi", "🇨🇩"),
    ("DJ", "Djibouti", "Djibouti", "Đông Phi", "Châu Phi", "🇩🇯"),
    ("EG", "Ai Cập", "Egypt", "Bắc Phi", "Châu Phi", "🇪🇬"),
    ("GQ", "Guinea Xích đạo", "Equatorial Guinea", "Trung Phi", "Châu Phi", "🇬🇶"),
    ("ER", "Eritrea", "Eritrea", "Đông Phi", "Châu Phi", "🇪🇷"),
    ("SZ", "Eswatini", "Eswatini", "Nam Phi", "Châu Phi", "🇸🇿"),
    ("ET", "Ethiopia", "Ethiopia", "Đông Phi", "Châu Phi", "🇪🇹"),
    ("GA", "Gabon", "Gabon", "Trung Phi", "Châu Phi", "🇬🇦"),
    ("GM", "Gambia", "Gambia", "Tây Phi", "Châu Phi", "🇬🇲"),
    ("GH", "Ghana", "Ghana", "Tây Phi", "Châu Phi", "🇬🇭"),
    ("GN", "Guinea", "Guinea", "Tây Phi", "Châu Phi", "🇬🇳"),
    ("GW", "Guinea-Bissau", "Guinea-Bissau", "Tây Phi", "Châu Phi", "🇬🇼"),
    ("CI", "Bờ Biển Ngà", "Ivory Coast", "Tây Phi", "Châu Phi", "🇨🇮"),
    ("KE", "Kenya", "Kenya", "Đông Phi", "Châu Phi", "🇰🇪"),
    ("LS", "Lesotho", "Lesotho", "Nam Phi", "Châu Phi", "🇱🇸"),
    ("LR", "Liberia", "Liberia", "Tây Phi", "Châu Phi", "🇱🇷"),
    ("LY", "Libya", "Libya", "Bắc Phi", "Châu Phi", "🇱🇾"),
    ("MG", "Madagascar", "Madagascar", "Đông Phi", "Châu Phi", "🇲🇬"),
    ("MW", "Malawi", "Malawi", "Đông Phi", "Châu Phi", "🇲🇼"),
    ("ML", "Mali", "Mali", "Tây Phi", "Châu Phi", "🇲🇱"),
    ("MR", "Mauritania", "Mauritania", "Tây Phi", "Châu Phi", "🇲🇷"),
    ("MU", "Mauritius", "Mauritius", "Đông Phi", "Châu Phi", "🇲🇺"),
    ("MA", "Morocco", "Morocco", "Bắc Phi", "Châu Phi", "🇲🇦"),
    ("MZ", "Mozambique", "Mozambique", "Đông Phi", "Châu Phi", "🇲🇿"),
    ("NA", "Namibia", "Namibia", "Nam Phi", "Châu Phi", "🇳🇦"),
    ("NE", "Niger", "Niger", "Tây Phi", "Châu Phi", "🇳🇪"),
    ("NG", "Nigeria", "Nigeria", "Tây Phi", "Châu Phi", "🇳🇬"),
    ("RW", "Rwanda", "Rwanda", "Đông Phi", "Châu Phi", "🇷🇼"),
    ("ST", "São Tomé và Príncipe", "São Tomé and Príncipe", "Trung Phi", "Châu Phi", "🇸🇹"),
    ("SN", "Senegal", "Senegal", "Tây Phi", "Châu Phi", "🇸🇳"),
    ("SC", "Seychelles", "Seychelles", "Đông Phi", "Châu Phi", "🇸🇨"),
    ("SL", "Sierra Leone", "Sierra Leone", "Tây Phi", "Châu Phi", "🇸🇱"),
    ("SO", "Somalia", "Somalia", "Đông Phi", "Châu Phi", "🇸🇴"),
    ("ZA", "Nam Phi", "South Africa", "Nam Phi", "Châu Phi", "🇿🇦"),
    ("SS", "Nam Sudan", "South Sudan", "Đông Phi", "Châu Phi", "🇸🇸"),
    ("SD", "Sudan", "Sudan", "Bắc Phi", "Châu Phi", "🇸🇩"),
    ("TZ", "Tanzania", "Tanzania", "Đông Phi", "Châu Phi", "🇹🇿"),
    ("TG", "Togo", "Togo", "Tây Phi", "Châu Phi", "🇹🇬"),
    ("TN", "Tunisia", "Tunisia", "Bắc Phi", "Châu Phi", "🇹🇳"),
    ("UG", "Uganda", "Uganda", "Đông Phi", "Châu Phi", "🇺🇬"),
    ("ZM", "Zambia", "Zambia", "Đông Phi", "Châu Phi", "🇿🇲"),
    ("ZW", "Zimbabwe", "Zimbabwe", "Nam Phi", "Châu Phi", "🇿🇼"),
    # Châu Đại Dương
    ("AU", "Úc", "Australia", "Châu Đại Dương", "Châu Đại Dương", "🇦🇺"),
    ("FJ", "Fiji", "Fiji", "Châu Đại Dương", "Châu Đại Dương", "🇫🇯"),
    ("KI", "Kiribati", "Kiribati", "Châu Đại Dương", "Châu Đại Dương", "🇰🇮"),
    ("MH", "Quần đảo Marshall", "Marshall Islands", "Châu Đại Dương", "Châu Đại Dương", "🇲🇭"),
    ("FM", "Micronesia", "Micronesia", "Châu Đại Dương", "Châu Đại Dương", "🇫🇲"),
    ("NR", "Nauru", "Nauru", "Châu Đại Dương", "Châu Đại Dương", "🇳🇷"),
    ("NZ", "New Zealand", "New Zealand", "Châu Đại Dương", "Châu Đại Dương", "🇳🇿"),
    ("PW", "Palau", "Palau", "Châu Đại Dương", "Châu Đại Dương", "🇵🇼"),
    ("PG", "Papua New Guinea", "Papua New Guinea", "Châu Đại Dương", "Châu Đại Dương", "🇵🇬"),
    ("WS", "Samoa", "Samoa", "Châu Đại Dương", "Châu Đại Dương", "🇼🇸"),
    ("SB", "Quần đảo Solomon", "Solomon Islands", "Châu Đại Dương", "Châu Đại Dương", "🇸🇧"),
    ("TO", "Tonga", "Tonga", "Châu Đại Dương", "Châu Đại Dương", "🇹🇴"),
    ("TV", "Tuvalu", "Tuvalu", "Châu Đại Dương", "Châu Đại Dương", "🇹🇻"),
    ("VU", "Vanuatu", "Vanuatu", "Châu Đại Dương", "Châu Đại Dương", "🇻🇺"),
]


async def seed():
    async with AsyncSessionLocal() as session:
        for code, name_vi, name_en, region, continent, flag in COUNTRIES:
            await session.execute(
                text("""
                    INSERT INTO countries (code, name_vi, name_en, region, continent, flag_emoji, scholarship_count)
                    VALUES (:code, :name_vi, :name_en, :region, :continent, :flag, 0)
                    ON CONFLICT (code) DO UPDATE SET
                        name_vi = EXCLUDED.name_vi,
                        name_en = EXCLUDED.name_en,
                        region = EXCLUDED.region,
                        continent = EXCLUDED.continent,
                        flag_emoji = EXCLUDED.flag_emoji
                """),
                {"code": code, "name_vi": name_vi, "name_en": name_en,
                 "region": region, "continent": continent, "flag": flag}
            )
        await session.commit()
        print(f"Seeded {len(COUNTRIES)} countries.")


if __name__ == "__main__":
    if sys.platform == "win32":
        import selectors
        asyncio.run(seed(), loop_factory=lambda: asyncio.SelectorEventLoop(selectors.SelectSelector()))
    else:
        asyncio.run(seed())
