"""initial

Revision ID: 60d309cfcce5
Revises: 
Create Date: 2026-05-07 22:09:56.585791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '60d309cfcce5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name_vi', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('continent', sa.String(length=50), nullable=True),
    sa.Column('flag_emoji', sa.String(length=10), nullable=True),
    sa.Column('scholarship_count', sa.Integer(), nullable=True),
    sa.Column('last_synced_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_code'), 'countries', ['code'], unique=True)
    op.create_index(op.f('ix_countries_continent'), 'countries', ['continent'], unique=False)
    op.create_table('country_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('capital_city', sa.String(length=100), nullable=True),
    sa.Column('major_study_cities', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('monthly_cost_usd_min', sa.Integer(), nullable=True),
    sa.Column('monthly_cost_usd_max', sa.Integer(), nullable=True),
    sa.Column('cost_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('climate_vi', sa.Text(), nullable=True),
    sa.Column('culture_vi', sa.Text(), nullable=True),
    sa.Column('safety_vi', sa.Text(), nullable=True),
    sa.Column('student_life_vi', sa.Text(), nullable=True),
    sa.Column('healthcare_vi', sa.Text(), nullable=True),
    sa.Column('visa_notes_vi', sa.Text(), nullable=True),
    sa.Column('post_grad_visa_vi', sa.Text(), nullable=True),
    sa.Column('job_search_duration_months', sa.Integer(), nullable=True),
    sa.Column('work_permit_notes_vi', sa.Text(), nullable=True),
    sa.Column('pr_pathway_vi', sa.Text(), nullable=True),
    sa.Column('job_market_demand_vi', sa.Text(), nullable=True),
    sa.Column('competition_level', sa.String(length=20), nullable=True),
    sa.Column('competition_notes_vi', sa.Text(), nullable=True),
    sa.Column('avg_starting_salary_usd', sa.Integer(), nullable=True),
    sa.Column('intl_student_success_vi', sa.Text(), nullable=True),
    sa.Column('pros_vi', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('cons_vi', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('data_confidence', sa.String(length=20), nullable=True),
    sa.Column('ai_generated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_info_country_code'), 'country_info', ['country_code'], unique=True)
    op.create_table('scholarships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('name_vi', sa.String(length=300), nullable=False),
    sa.Column('name_en', sa.String(length=300), nullable=False),
    sa.Column('provider', sa.String(length=200), nullable=True),
    sa.Column('coverage_type', sa.String(length=20), nullable=False),
    sa.Column('coverage_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('monthly_stipend_usd', sa.Integer(), nullable=True),
    sa.Column('duration_years', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('language_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('academic_requirements', sa.Text(), nullable=True),
    sa.Column('age_limit', sa.Integer(), nullable=True),
    sa.Column('nationality_eligible', sa.Text(), nullable=True),
    sa.Column('application_deadline', sa.String(length=100), nullable=True),
    sa.Column('application_url', sa.Text(), nullable=True),
    sa.Column('official_website', sa.Text(), nullable=True),
    sa.Column('description_vi', sa.Text(), nullable=True),
    sa.Column('requirements_vi', sa.Text(), nullable=True),
    sa.Column('tips_vi', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('data_confidence', sa.String(length=20), nullable=True),
    sa.Column('ai_generated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholarships_country_code'), 'scholarships', ['country_code'], unique=False)
    op.create_index(op.f('ix_scholarships_coverage_type'), 'scholarships', ['coverage_type'], unique=False)
    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('triggered_by', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('scholarships_found', sa.Integer(), nullable=True),
    sa.Column('scholarships_upserted', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('claude_model', sa.String(length=50), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_logs_country_code'), 'sync_logs', ['country_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_logs_country_code'), table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_index(op.f('ix_scholarships_coverage_type'), table_name='scholarships')
    op.drop_index(op.f('ix_scholarships_country_code'), table_name='scholarships')
    op.drop_table('scholarships')
    op.drop_index(op.f('ix_country_info_country_code'), table_name='country_info')
    op.drop_table('country_info')
    op.drop_index(op.f('ix_countries_continent'), table_name='countries')
    op.drop_index(op.f('ix_countries_code'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
